---
- name: Ensure jailed user exists.
  user:
    name: "{{ item.name }}"
    password: "{{ item.password | default(omit) }}"
    groups: "{{ item.groups | default(omit) }}"
    append: true
    shell: "{{ item.shell | default(omit) }}"
    home: "{{ item.home | default(omit) }}"
    createhome: "{{ item.createhome | default(omit) }}"
  register: user_task

- name: Ensure jailed user has a homedir inside the jail (if configured).
  file:
    path: "{{ ssh_chroot_jail_path }}{{ item.home }}"
    state: directory
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: 0755
  when: item.home is defined

- name: Ensure account skeleton files are copied into jailed user's home.
  block:
    - name: Copy the skeleton files into jailed user's home.
      command: "cp -r -n /etc/skel/. {{ ssh_chroot_jail_path }}{{ item.home }}"
      args:
        warn: false
      failed_when: false

    - name: Set the correct ownership for the files into jailed user's home.
      ansible.builtin.file:
        path: "{{ ssh_chroot_jail_path }}{{ item.home }}"
        state: directory
        owner: "{{ item.name }}"
        group: "{{ item.name }}"
        mode: 0755
        recurse: true
  when:
    - item.home is defined
    - user_task.changed
